import { FewShotExample } from '../types/ai';

export const fewShotExamples: FewShotExample[] = [
  {
    input: {
      Name: 'John Doe',
      Email: 'john@example.com',
      Phone: '+1-555-1234',
      Company: 'Acme Inc',
      City: 'New York',
      State: 'NY',
      Country: 'USA',
      Notes: 'Interested in premium plan, wants demo next week',
    },
    output: {
      created_at: '2026-07-10T10:00:00.000Z',
      name: 'John Doe',
      email: 'john@example.com',
      country_code: '+1',
      mobile_without_country_code: '555-1234',
      company: 'Acme Inc',
      city: 'New York',
      state: 'NY',
      country: 'USA',
      lead_owner: '-',
      crm_status: 'GOOD_LEAD_FOLLOW_UP',
      crm_note: 'Interested in premium plan, wants demo next week',
      data_source: 'leads_on_demand',
      possession_time: '-',
      description: 'Interested in premium plan, wants demo next week',
    },
  },
  {
    input: {
      'Full Name': 'Jane Smith',
      'Email Addresses': 'jane@work.com, jane.personal@gmail.com',
      Phone: '9876543210',
      'Mobile 2': '8765432109',
    },
    output: {
      created_at: '2026-07-10T10:00:00.000Z',
      name: 'Jane Smith',
      email: 'jane@work.com',
      country_code: '-',
      mobile_without_country_code: '9876543210',
      company: '-',
      city: '-',
      state: '-',
      country: '-',
      lead_owner: '-',
      crm_status: 'GOOD_LEAD_FOLLOW_UP',
      crm_note: 'Additional emails: jane.personal@gmail.com. Additional phones: 8765432109',
      data_source: '-',
      possession_time: '-',
      description: '-',
    },
  },
  {
    input: {
      Name: 'No Contact Info',
      Company: 'Some Corp',
      Notes: 'Just a company note',
    },
    output: {
      skip: true,
      reason: 'No email or mobile found',
    },
  },
  {
    input: {
      Timestamp: '2026-05-13 14:20:48',
      Name: 'Rajesh Patel',
      Email: 'rajesh@example.com',
      'Phone Number': '+91 9876543212',
      Organization: 'Startup Inc',
      Location: 'Delhi',
      'Lead Source': 'Facebook Ad',
      Comments: 'Not interested in our services right now',
    },
    output: {
      created_at: '2026-05-13T14:20:48.000Z',
      name: 'Rajesh Patel',
      email: 'rajesh@example.com',
      country_code: '+91',
      mobile_without_country_code: '9876543212',
      company: 'Startup Inc',
      city: 'Delhi',
      state: '-',
      country: '-',
      lead_owner: '-',
      crm_status: 'BAD_LEAD',
      crm_note: 'Lead Source: Facebook Ad',
      data_source: '-',
      possession_time: '-',
      description: 'Not interested in our services right now',
    },
  },
];
